[package]
name = "ft-nmr-spectrometer-control"
version = "0.1.0"
license = "MIT OR Apache-2.0"
authors = [ "Florian Beck <info@florian-beck.de>" ]
build = "build.rs"
edition = "2021"

[build-dependencies]
slint-build = "1.1"

[dependencies]
slint = "1.1"
