export component Circle {
    in property border <=> p.stroke;
    in property background <=> p.fill;

    p:= Path {
        width: 100%;
        height: 100%;
        stroke-width: 1px;

        MoveTo {
            x: 0;
            y: 1;
        }
        ArcTo {
            radius-x: 1;
            radius-y: 1;
            x: 2;
            y: 1;
        }
        ArcTo {
            radius-x: 1;
            radius-y: 1;
            x: 0;
            y: 1;
        }
        Close {}
    }
}